name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag uptimerobot-api-status-switcher:$(date +%s)
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build image and push to Docker Hub and GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
          # relative path to the place where source code with Dockerfile is located
       # context: ./
          # Note: tags has to be all lower-case
        tags: |
          pknw1/uptimerobot-api-status-switcher:latest
          pknw1/uptimerobot-api-status-switcher:$GITHUB_JOB
        push: true

